### ISSUE TITLE
EntityManager: incorrect merging of bases when modification is in grandparent

### ISSUE THREAD

**Issue by dmlary** [dmlary/morrow#90]
Given the following entities:
```yml
- id: spec:collide/result
  base:
  - 'spec:collide/left'
  - 'spec:collide/right'

- id: spec:collide/left
  base: spec:collide/left_parent
  components:
  - viewable:
      short: from left

- id: spec:collide/left_parent

- id: spec:collide/right
  base: spec:collide/right_parent

- id: spec:collide/right_parent
  components:
  - viewable:
      short: from right parent
```

We would expect `spec:collide/result` to have short description `from right parent`, but currently it gives the value `from left`.

```txt
[1] pry(Morrow::Console)> entity_components('spec:collide/result')
=> [#<Morrow::Component::Metadata:0x00007fcb4fd3bea0
  @__modified_base=true,
  @area=nil,
  @base=["spec:collide/left", "spec:collide/right"],
  @source=nil,
  @spawned_by=nil>,
 #<Morrow::Component::Viewable:0x00007fcb4fd3bb08 @contents=false, @desc=nil, @formatter=nil, @long=nil, @short="from left">]
```
